site_name: note
site_description: 学习笔记
site_url: https://note.malinkang.com/
site_author: malinkang
## Repository
repo_name: malinkang/note
repo_url: https://github.com/malinkang/note

# Copyright
copyright: Copyright &copy; 2013 - 2021 malinkang

theme:
  name: null
  custom_dir: !ENV [THEME_DIR, "material"]
  logo: https://avatars.githubusercontent.com/u/3365208?v=4
  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  
  features:
    - content.code.annotate-code
    - navigation.tabs
    - navigation.top
  palette:
    - scheme: default
      primary: light-blue
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    logo: logo
  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/malinkang
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/malinkang
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/malinkang
    - icon: fontawesome/brands/telegram
      link: https://t.me/malinkang
    - icon: fontawesome/brands/weibo
      link: https://weibo.com/malinkang
    - icon: fontawesome/brands/medium
      link: https://medium.com/malinkang

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - android:
    - 四大组件:
      - BroadcastReceiver: android/四大组件/broadcastreceiver.md
      - Service: android/四大组件/service.md
      - Activity: android/四大组件/activity.md
    - AOSP:
      - Activity启动流程: android/aosp/start-activity.md
      - ArrayMap: android/aosp/arraymap.md
    - 三方源码:
      - Retrofit源码分析: android/三方源码/retrofit.md
      - LeakCanary: android/三方源码/leakcanary.md
    - 性能优化:
      - Matrix源码分析: android/性能优化/matrix.md
    - 数据存储:
      - SharedPreference: android/数据存储/sharedpreference.md
    - Jetpack:
      - Navigation使用: android/jetpack/navigation.md
  - java:
    - Effective Java:
      - 2013-03-16-serialization: java/effective java/serialization.md
      - 2013-03-09-concurrency: java/effective java/concurrency.md
      - 2013-03-02-exceptions: java/effective java/exceptions.md
      - 2013-02-23-general-programming: java/effective java/general-programming.md
      - 2013-02-16-methods: java/effective java/methods.md
      - 2013-02-09-lambdas-and-streams: java/effective java/lambdas-and-streams.md
      - 2013-02-02-enums-and-annotations: java/effective java/enums-and-annotations.md
      - 2013-01-26-generics: java/effective java/generics.md
      - 2013-01-19-classes-and-interfaces: java/effective java/classes-and-interfaces.md
      - 2013-01-12-methods-common-to-all-objects: java/effective java/methods-common-to-all-objects.md
      - 2013-01-05-creating-and-destroying-objects: java/effective java/creating-and-destroying-objects.md
  - leetcode:
    - 排序:
      - 插入排序: leetcode/排序/insertion-sort.md
      - 冒泡排序: leetcode/排序/bubble-sort.md
    - 数组:
      - 830. 较大分组的位置: leetcode/数组/830.positions-of-large-groups.md
      - 448.找到所有数组中消失的数字: leetcode/数组/448.find-all-numbers-disappeared-in-an-array.md
      - 349. 两个数组的交集: leetcode/数组/349.intersection-of-two-arrays.md
      - 283.移动零: leetcode/数组/283.move-zeroes.md
      - 169.多数元素: leetcode/数组/169.majority-element.md
      - 119.杨辉三角 II: leetcode/数组/119.pascals-triangle-ii.md
      - 118.杨辉三角: leetcode/数组/118.pascals-triangle.md
      - 88.合并两个有序数组: leetcode/数组/88.merge-sorted-array.md
      - 66.加一: leetcode/数组/66.plus-one.md
      - 48.旋转图像: leetcode/数组/48.rotate-image.md
      - 31.下一个排列: leetcode/数组/31.next-permutation.md
      - 29. 顺时针打印矩阵: leetcode/数组/29.shun-shi-zhen-da-yin-ju-zhen-lcof.md
      - 27.移除元素: leetcode/数组/27.remove-element.md
      - 26.删除排序数组中的重复项: leetcode/数组/26.remove-duplicates-from-sorted-array.md
      - 21.调整数组顺序使奇数位于偶数前面: leetcode/数组/21.tiao-zheng-shu-zu-shun-xu-shi-qi-shu-wei-yu-ou-shu-qian-mian-lcof.md
      - 15. 三数之和: leetcode/数组/15.3sum.md
      - 11.盛最多水的容器: leetcode/数组/11.container-with-most-water.md
      - 剑指 Offer 03.数组中重复的数字: leetcode/数组/3.shu-zu-zhong-zhong-fu-de-shu-zi-lcof.md
      - 1.两数之和: leetcode/数组/1.two-sum.md
